---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  RepositoryName:
    Type: String
  ParentServiceStack:
    Type: String
  DevelopmentAccountId:
    Description: 'The development account id which needs access to the repository'
    Type: String
  ProductionAccountId:
    Description: 'The production account id which needs access to the repository'
    Type: String    

Resources:
  Repository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          -
            Sid: AllowDockerImagePull
            Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${DevelopmentAccountId}:root'
                - !Sub 'arn:aws:iam::${ProductionAccountId}:root'
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"

Outputs:
  ServiceName:
    Description: 'The Name of the repository for storing docker images'
    Value: !Ref Repository
    Export:
      Name: !Sub '${ParentServiceStack}-RepositoryName'
